// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpHost) DeepCopyInto(out *DnsmasqDhcpHost) {
	*out = *in
	if in.Macs != nil {
		in, out := &in.Macs, &out.Macs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientIDs != nil {
		in, out := &in.ClientIDs, &out.ClientIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SetTags != nil {
		in, out := &in.SetTags, &out.SetTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpHost.
func (in *DnsmasqDhcpHost) DeepCopy() *DnsmasqDhcpHost {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpHostSet) DeepCopyInto(out *DnsmasqDhcpHostSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpHostSet.
func (in *DnsmasqDhcpHostSet) DeepCopy() *DnsmasqDhcpHostSet {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpHostSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsmasqDhcpHostSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpHostSetList) DeepCopyInto(out *DnsmasqDhcpHostSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DnsmasqDhcpHostSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpHostSetList.
func (in *DnsmasqDhcpHostSetList) DeepCopy() *DnsmasqDhcpHostSetList {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpHostSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsmasqDhcpHostSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpHostSetSpec) DeepCopyInto(out *DnsmasqDhcpHostSetSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]DnsmasqDhcpHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpHostSetSpec.
func (in *DnsmasqDhcpHostSetSpec) DeepCopy() *DnsmasqDhcpHostSetSpec {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpHostSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpHostSetStatus) DeepCopyInto(out *DnsmasqDhcpHostSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpHostSetStatus.
func (in *DnsmasqDhcpHostSetStatus) DeepCopy() *DnsmasqDhcpHostSetStatus {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpHostSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpOption) DeepCopyInto(out *DnsmasqDhcpOption) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpOption.
func (in *DnsmasqDhcpOption) DeepCopy() *DnsmasqDhcpOption {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpOptionSet) DeepCopyInto(out *DnsmasqDhcpOptionSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpOptionSet.
func (in *DnsmasqDhcpOptionSet) DeepCopy() *DnsmasqDhcpOptionSet {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpOptionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsmasqDhcpOptionSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpOptionSetList) DeepCopyInto(out *DnsmasqDhcpOptionSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DnsmasqDhcpOptionSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpOptionSetList.
func (in *DnsmasqDhcpOptionSetList) DeepCopy() *DnsmasqDhcpOptionSetList {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpOptionSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsmasqDhcpOptionSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpOptionSetSpec) DeepCopyInto(out *DnsmasqDhcpOptionSetSpec) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]DnsmasqDhcpOption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpOptionSetSpec.
func (in *DnsmasqDhcpOptionSetSpec) DeepCopy() *DnsmasqDhcpOptionSetSpec {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpOptionSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqDhcpOptionSetStatus) DeepCopyInto(out *DnsmasqDhcpOptionSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqDhcpOptionSetStatus.
func (in *DnsmasqDhcpOptionSetStatus) DeepCopy() *DnsmasqDhcpOptionSetStatus {
	if in == nil {
		return nil
	}
	out := new(DnsmasqDhcpOptionSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqHost) DeepCopyInto(out *DnsmasqHost) {
	*out = *in
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqHost.
func (in *DnsmasqHost) DeepCopy() *DnsmasqHost {
	if in == nil {
		return nil
	}
	out := new(DnsmasqHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqHostSet) DeepCopyInto(out *DnsmasqHostSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqHostSet.
func (in *DnsmasqHostSet) DeepCopy() *DnsmasqHostSet {
	if in == nil {
		return nil
	}
	out := new(DnsmasqHostSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsmasqHostSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqHostSetList) DeepCopyInto(out *DnsmasqHostSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DnsmasqHostSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqHostSetList.
func (in *DnsmasqHostSetList) DeepCopy() *DnsmasqHostSetList {
	if in == nil {
		return nil
	}
	out := new(DnsmasqHostSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsmasqHostSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqHostSetSpec) DeepCopyInto(out *DnsmasqHostSetSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]DnsmasqHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqHostSetSpec.
func (in *DnsmasqHostSetSpec) DeepCopy() *DnsmasqHostSetSpec {
	if in == nil {
		return nil
	}
	out := new(DnsmasqHostSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqHostSetStatus) DeepCopyInto(out *DnsmasqHostSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqHostSetStatus.
func (in *DnsmasqHostSetStatus) DeepCopy() *DnsmasqHostSetStatus {
	if in == nil {
		return nil
	}
	out := new(DnsmasqHostSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqOption) DeepCopyInto(out *DnsmasqOption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqOption.
func (in *DnsmasqOption) DeepCopy() *DnsmasqOption {
	if in == nil {
		return nil
	}
	out := new(DnsmasqOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqOptionSet) DeepCopyInto(out *DnsmasqOptionSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqOptionSet.
func (in *DnsmasqOptionSet) DeepCopy() *DnsmasqOptionSet {
	if in == nil {
		return nil
	}
	out := new(DnsmasqOptionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsmasqOptionSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqOptionSetList) DeepCopyInto(out *DnsmasqOptionSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DnsmasqOptionSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqOptionSetList.
func (in *DnsmasqOptionSetList) DeepCopy() *DnsmasqOptionSetList {
	if in == nil {
		return nil
	}
	out := new(DnsmasqOptionSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsmasqOptionSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqOptionSetSpec) DeepCopyInto(out *DnsmasqOptionSetSpec) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]DnsmasqOption, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqOptionSetSpec.
func (in *DnsmasqOptionSetSpec) DeepCopy() *DnsmasqOptionSetSpec {
	if in == nil {
		return nil
	}
	out := new(DnsmasqOptionSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsmasqOptionSetStatus) DeepCopyInto(out *DnsmasqOptionSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsmasqOptionSetStatus.
func (in *DnsmasqOptionSetStatus) DeepCopy() *DnsmasqOptionSetStatus {
	if in == nil {
		return nil
	}
	out := new(DnsmasqOptionSetStatus)
	in.DeepCopyInto(out)
	return out
}
