# permissions for end users to view dhcphosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dhcphosts-viewer-role
rules:
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dhcphosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dhcphosts/status
  verbs:
  - get
