# permissions for end users to view dhcpoptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dhcpoptions-viewer-role
rules:
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dhcpoptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dhcpoptions/status
  verbs:
  - get
