# permissions for end users to edit dnsmasqoptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsmasqoptions-editor-role
rules:
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqoptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqoptions/status
  verbs:
  - get
