# permissions for end users to view dnsmasqoptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsmasqoptions-viewer-role
rules:
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqoptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqoptions/status
  verbs:
  - get
